import BasicLogo from "@/app/client/components/basic-logo";
import { Ubuntu } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="mx-auto h-screen px-2 md:w-[90%] md:px-0 lg:w-[65%]">
      <div className="text-dark flex flex-col  h-screen w-full items-center justify-center">
        <div className="pb-6" >
          <BasicLogo />
        </div>
        {children}
      </div>
    </div>
  );
}
