import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import QueryClientServerProvider from "../client/context/query-client-provider";
import { AuthenticationProvider } from "../client/hooks/use-auth";

const poppins = Poppins({ weight: "400", subsets: ["devanagari"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientServerProvider>
      <AuthenticationProvider>
        <html lang="es">
          <body className={poppins.className}>
            <div className="mx-auto h-screen text-sm md:px-0">{children}</div>
          </body>
        </html>
      </AuthenticationProvider>
    </QueryClientServerProvider>
  );
}
